// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback:                       1
// Total number of exported functions:  17

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    xn_nft
    (
        createNft
        burn
        transfer
        claimRoyaltiesFromMarketplace
        updateInternalValue
        state
        token_details
        getTokenSubscriptionStatus
        issueToken
        setLocalRoles
        buyNft
        getNftPrice
        updateAuthority
        admins
        maintainers
        callBack
    )
}
