// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    price_oracle
    (
        get_price
        set_price
    )
}

elrond_wasm_node::wasm_empty_callback! {}
