[package]
name = "price_oracle-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Tarun Jaiswal <tarunjais28@gmail.com>"]

[dev-dependencies]

[dependencies.price_oracle]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.37.0"
